image: registry.gitlab.com/bitfireat/docker-android-emulator:latest

before_script:
  - git submodule update --init --recursive
  - export GRADLE_USER_HOME=`pwd`/.gradle; chmod +x gradlew

cache:
  paths:
     - .gradle/

test:
  script:
    - ./gradlew app:lint
  artifacts:
    paths:
      - app/build/outputs/lint-results-debug.html
      - app/build/reports
      - build/reports

